name: 'Terraform CI'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install ZIP
        run: sudo apt-get update && sudo apt-get install zip -y

      - name: Zip Function Code
        run: |
          zip -r function.zip ./services/ad_score/src/functions
          mv function.zip ./services/ad_score/terraform/

      - name: Upload Model and Config Directories to GCS
        run: |
          gsutil -m cp -r ./services/ad_score/src/model gs://${{ secrets.GCS_BUCKET_NAME }}/model/
          gsutil -m cp -r ./services/ad_score/src/config gs://${{ secrets.GCS_BUCKET_NAME }}/config/
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_key.json

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}      

      - name: Write GCP Key to File
        run: echo '${{ secrets.GCP_SA_KEY }}' > ${{ github.workspace }}/gcp_key.json
      
      - name: Create terraform.rc file for Terraform Cloud Credentials
        run: |
          echo "credentials \"app.terraform.io\" {" > ${{ github.workspace }}/terraform.rc
          echo "  token = \"${{ secrets.TF_CLOUD_TOKEN }}\"" >> ${{ github.workspace }}/terraform.rc
          echo "}" >> ${{ github.workspace }}/terraform.rc

      - name: Terraform Init
        run: terraform init
        working-directory: services/ad_score/terraform
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_key.json
          TF_CLI_CONFIG_FILE: ${{ github.workspace }}/terraform.rc

      - name: Print Current Directory
        run: pwd

      - name: List Directory Contents
        run: ls -la services/ad_score/src/functions

      - name: Terraform Plan
        run: |
          gcp_credentials=$(cat /home/runner/work/demo/demo/gcp_key.json)
          terraform plan -var="google_credentials=${gcp_credentials}"
        working-directory: services/ad_score/terraform
        env:
          TF_CLI_CONFIG_FILE: ${{ github.workspace }}/terraform.rc


      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' || (github.ref == 'refs/heads/test_main' && github.event_name == 'push')
        run: |
          gcp_credentials=$(cat ${{ github.workspace }}/gcp_key.json)
          terraform apply -auto-approve -var="google_credentials=${gcp_credentials}"
        working-directory: services/ad_score/terraform
        env:
          TF_CLI_CONFIG_FILE: ${{ github.workspace }}/terraform.rc
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_key.json

